// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PianoChordSearchController from "./piano_chord_search_controller.js"
application.register("piano-chord-search", PianoChordSearchController)

import PianoScaleSearchController from "./piano_scale_search_controller.js"
application.register("piano-scale-search", PianoScaleSearchController)

import Notification from 'stimulus-notification'
application.register('notification', Notification)
