databases:
  - name: mtdb
    databaseName: mtdb
    user: mtdb

services:
  - type: web
    name: mtdb
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mtdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
