default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mtdb_development
  host: localhost
  port: 5434
  username: postgres
  password: password

test:
  <<: *default
  database: mtdb_test
  host: localhost
  port: 5434
  username: postgres
  password: password

production:
  <<: *default
  database: mtdb_production
  username: mtdb
  password: <%= ENV["MTDB_DATABASE_PASSWORD"] %>
